### ISSUE TITLE
import() proposal accepted

### ISSUE THREAD

**Issue by enten** [mkyurchev/babel-plugin-transform-system-import-commonjs#1]
The [`import()` proposal](https://github.com/tc39/proposal-dynamic-import) was accepted.

Is this plugin will be updated in consequence?

**Comment by pwmckenna** [comment]
Just published [babel-plugin-transform-import-commonjs@1.0.0](https://www.npmjs.com/package/babel-plugin-transform-import-commonjs), which is just a [slightly modified fork](https://github.com/pwmckenna/babel-plugin-transform-import-commonjs). @enten, its all your code so if you want it I can just transfer the repo to you. I'll also be using up the npm name, but that's of course yours as well if you'd like it.

**Comment by kiurchv** [comment]
@pwmckenna, thanks for your work! It will be right to deprecate current plugin in favor to your fork, I'll add deprecation notice shortly

**Comment by kiurchv** [comment]
Also, it seems that similar functionality should appear in the babel's [transform-es2015-modules-commonjs](https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-es2015-modules-commonjs) plugin when babel/babel#4986 will be merged.

**Comment by pwmckenna** [comment]
oh very cool, that'll be perfect. that PR is a monster though!

**Comment by enten** [comment]
Thanks for your work sirs!

@pwmckenna

> Its all your code so if you want it I can just transfer the repo to you. I'll also be using up the npm name, but that's of course yours as well if you'd like it.

No thanks my good sir. It's not necessary. Except if you don't want to keep the package up to date while a long time period.
